### PR TITLE
Prove symlinks to files and directories do work

### PR DESCRIPTION
**Pull request by rec**
Tiny change...

This proves that the AppEngine does follow relative symlinks to directories and files.

Our plan is only to use directories (i.e only import modules) but good to know either way...

### CODE REVIEW

**Comment by andrewburgess** [comment]
Doesn't work on Windows, but that was expected. Might add an ant script at some point if I want to do development on my laptop

**Comment by rec** [comment]
Hmph, it's supposed to work on Mac and Windows!

Apparently the correct command is mklink and theoretically github should do it all correctly.

I'll fire up a virtual machine tomorrow perhaps to check it out... it's not immediately important!

**Comment by andrewburgess** [comment]
It essentially just made a new file with the relative directory as the contents

**Comment by rec** [comment]
All right, did some more searching and apparently this is a known windows/git issue - one that's supposed to be fixed "soon" but who knows, really?  I'd been looking at the thread a year ago but it doesn't seem much as happened.

I'm thinking I might abandon the original directory structure just for the sake of expediency, I'll sleep on it.

**Comment by andrewburgess** [comment]
Is this pull request still active?

**Comment by rec** [comment]
It is dead - we're not doing this because it doesn't work on Windows.

In future, I'll send a message saying, "Killing this request".

I thought I deleted the branch, will make sure it's gone tomorrow!

**Comment by rec** [comment]
closed.

**Pull request closed without merging**
