### PR TITLE
Reworked Some Project Structure

### PR DESCRIPTION
**Pull request by andrewburgess**
Retooled things a bit so that there is a "common" directory where the web app is developed.

When building the Android version, there is an Ant task that executes that will copy in the www folder to the assets directory of the project before doing the actual build.

This way I can develop the web app portion primarily in a browser before deploying to the mobile platform

### CODE REVIEW

**Comment by rec** [comment]
Sorry for the delays, too many stupid chores.  :-(

Remembering that email doesn't convey tone of voice :-D that this is all in the spirit of "wrangling to see what's the best".  In particular, decisions at the early phases do have a way of biting one later.

So you're solving the issue of moving things around with a build!

There's already an ant build, so this is a convenient way to do things.

There's one important trap that we have to avoid - where the file you see in a debugger or similar is the "temporary" file that's copied by the build.  It's really tempting to play with that file until your issue is fixed - and then the change is overwritten by a later build.

If we can possibly use some sort of symbolic link, that's always the best way.  It seems dangerous because links are dangerous, but links are dangerous precisely because they are so very powerful - with disciplined use, they really are the correct solution to "the same file in two places".

Heck, that's how git manages to do (part of) its magic - if it's good enough for them, it's good enough for us!

Just to be pedantic, "www" isn't actually a technically meaningful term - there's no "www" protocol or anything - it's a marketing buzzword!  It's also long to say - nine syllables.

You can think of that directory as serving http and https requests - and call it http - or, perhaps better, you can think of it as serving files with type html/text and call it html.

There's a hidden assumption, too, by calling a directory www that all of our products share a common root that is exposed to the web.  This is probably in fact true - no, in fact, I'm going to make it an axiom that, until further notice, all of our products share a common http root!  But perhaps we shouldn't build this into the naming.

Now, I believe that the Android build wants www somewhere (right?) but that's an even better argument for us distinguishing their directory, named www, from our directory, named http or html.

**Comment by andrewburgess** [comment]
Regarding the "temporary" files and debugging: it's pretty much impossible to do any actual debugging on the mobile devices, so I figured we would be safe in that aspect since editing them wouldn't give me any extra benefit. The only way to do debugging is to actually open up a web browser and use some sort of built in tool (firebug or chrome developer tools)

Symlinks would be useful, but my laptop is Windows based and I'm going to develop using that pretty regularly. I do know XCode can reference directories outside of the main "project" directory

And then the www directory, it's what Phonegap expects, so I figured I would just leave it as that. I don't really see the benefit of changing the name

**Comment by rec** [comment]
Awright, absolutely, if you're often doing this on a non-Windows environment then symlinks are out!  

Effectiveness is really the key here... the least amount of structure we can get away with (which is often unfortunately "rather a lot" because you need structure to get things done).

The build is the logical place to put this - it already exists and you are already "gathering together disparate items into a package" as part of it.  Fine.

Unfortunately, I'm going to have to come up with a different solution for the App Engine stuff (eventually, after the "exploratory phase") - when you run their local test server, it's constantly watching a directory with code and various files in it and recompiles it on the fly.

It's likely I can just set "include paths" or something like that.  Anyway, I'll burn that bridge when I get to it.  ;-)

[html vs web]

> I don't really see the benefit of changing the name

Well... there's a tiny technical advantage to calling it html, because then there's a nice correspondence between directory name and file suffix. 

css files live in the directory called css and have a .css suffix, html files live in the directory called html and have a .html suffix, js files live in the directory called js and have a .js suffix.

That seems really nice and regular for me, and I hate having special cases in the scripts that we will no doubt have to make at some point or other.

The other reason is that the phrase "www" _doesn't mean anything_ - it has no technical meaning at all, it's just an advertising buzzword.  It means, "er, the internet" - there are no "www files" or "www servers" or "www processors" or "www browsers" - there are html browsers that use http or https as a transport layer.

I am not a naturally precise person and when I started working with engineers I used to drive them nuts, confusing storage with memory and that sort of thing.  But I discovered through bitter experience that it's always a good idea to be almost pedantically precise, and to be as boringly regular as you can in your naming.

**Comment by andrewburgess** [comment]
Are you suggesting though that I move everything out of the www folder and into folders based on extension? Doing that will make development much more tedious primarily because I lose my main development environment (web browser) or I have to constantly change paths between developing and building

If the folder just needs to be renamed, then no big deal

**Comment by rec** [comment]
Oh, and one more comment - or nit-pick.  :-D

The build files for the android are appearing in the src tree.

I still think it's a good idea to have the build files in a separate subdirectory called "target".

Basically, everyone can know about src/, but "target/android/" is where all your android-only build things go - probably including things like intermediate files, .jar files or whatever (yes, it'd be nice to get them into "gen" but often it's not worth the time).

So "target/android" would be "the root of your Eclipse workarea" and you can put whatever you like there.

I'm using it in my other cross-platform app with two platforms, and it's really effective.

And it preserves the mapping of "file suffix -> directory name" which I seem to like so much.  :-D

**Comment by rec** [comment]
regarding source directories - just proposing changing www to html, everything else is fine, it'd be too annoying to move js and css elsewhere!

I'm also, separately, proposing moving the `src/android` to `target/android` unless it's a lot of work.  You aren't relying on the Android directory _including_ the source files any more, so it shouldn't be hard...?

It's simply convenient and practical to have src and target separate - because they end up being so very different in practice.

For example, in my other project with Warren, which only has two targets and not four like ours, look at this:

$ du -sk target src
1203880 target
4220    src

1.2 gigs vs 4 megs!  (Most of those are .gitignored...)

and yet 98%+ of my work is in "src".

So I frequently grep through all of src (I might be searching for "all uses of an html id tag") but I always avoid grepping through target.

Again, these things can be hard to change once they're set, so might as well think about 'em now.  Getting into a smooth, sustainable workflow is worth being a bit fussy at the start.

**Comment by andrewburgess** [comment]
How does this look? If good, I'll go ahead and merge it in and remove the branch

**Comment by rec** [comment]
All right!  "Looks good to me".

I learned a lot from this.

Er, now let me go back to that workflow article and see what happens next...  :-)

**Comment by rec** [comment]
All right!

So from the article it looks as if you should do the Merge Pull and then push this branch back into master.

That would be the signal to "deploy" which would mean either making a master build, or pushing to the server (or both) but right now we don't have that.

So Merge it back into master and then I'll pull.

Should I "close" this Pull Request, do you think?

**Comment by andrewburgess** [comment]
Yep, once merged, this should be closed. I'll also delete the branch at some point since there's no reason to keep around such auxiliary branches in my opinion. Anything branch that has significant development work should be kept, but experimental branches and ones used for restructuring should be removed once completed, yes?

**Comment by rec** [comment]
We should definitely delete the branch. I hope it doesn't delete the pull request, but my guess is not.  One way to find out!

Also, after deleting pls. respond in this thread (if you can :-D ) a tiny sketch of the steps you made to delete the branch from github and your local client - just so we have it in a single place to point to people (and I know Warren has really not used github at all and it's pretty mazy...)

Don't worry, most pull requests won't be this chatty.  :-)

**Comment by andrewburgess** [comment]
To delete a branch:

```
git branch -d branch-name
git push origin --delete branch-name
```

These two commands will delete both the local and the remote branch

**Comment by rec** [comment]
AH!  I've wanted to know that second one for a while now!!!

As I said, I've learned a lot.

**Comment by andrewburgess** [comment]
The --delete flag is syntactic sugar added in Git 1.7 for the original command

```
git push origin :branch-name
```

**Pull request merged**
