### PR TITLE
First protocol buffers

### PR DESCRIPTION
**Pull request by rec**
These introduce the first protocol buffers and a bash script for compiling them.  

Let's not worry right today about getting Andrew to compile protocol buffer definitions - for one thing, I need to make sure that I really can send these around easily in the AppEngine.

However, these files do actually compile, I checked 'em.

I understand this format is new to both of you, please ask me a lot of questions!

### CODE REVIEW

**Comment by andrewburgess** [comment]
Is it really beneficial to use protocol buffers? Since our application is going to be primarily Javascript based and JSON is so easy to use in Javascript, wouldn't it be easier to store things as JSON? I don't think the size difference is all that much. Plus, Python can handle JSON pretty easily as well

**Comment by rec** [comment]
Very good question, one I've been pondering myself.

We do need to somehow specify the data structures we're going to use!  So .proto is as good a format as any.

I decided to write these as .proto files because this is a convenient and unambiguous data description language that I already know, and one that maps onto JSON.

Think of this as a "JSON specification language" :-D as far as the front end goes.

With respect to the backend, the protocol compiler will give us Python and Java definition files automatically, so we can directly use these classes in Python or Java - if we choose.

It will depend probably on if there's a neat way to go from "Protocol Buffer definition" to "persistent data in the app engine" automatically.  I know that data _is not_ stored as protocol buffers in the App Engine's persistent data store, but I think there's a near-trivial way to map one to the other.

IF that works, then we'll certainly use them - because you can just go into one of those files, add a line, and get the equivalent of "a new column", and one which will automatically spit out the JSON we need.

**Comment by andrewburgess** [comment]
This should work. I was just thinking about how easy it is to work with JSON in Javascript. I think if the server can convert JSON to Protobuf to manipulate and work with, then that would be fine

**Comment by rec** [comment]
Our "transport layer" will always be JSON - as you say, so easy to work with!

We probably won't ever use the Java proto definitions - we're only using Java as generated code for the Android, so there's no need for them.

I removed them from the build, it'd be two seconds' work to put 'em back if we for some reason needed them.  Now it's only Python!

**Comment by rec** [comment]
So (unfortunately) it looks as if expecting to use protocol buffers in the App Engine is not reasonable.

I'll check this in but we should only expect to use this for informational purposes.

I'll next "port" this to the AppEngine datastore Property type, which should be pretty easy.  Stay tuned!

**Pull request merged**
