### PR TITLE
Initial Start Up Page

### PR DESCRIPTION
**Pull request by andrewburgess**
I've set up the necessary framework using jQuery Mobile

One thing I've noticed though is that it's kind of slow on my Android phone (original Droid). If that's not a huge deal at the moment, then I will continue along. I think part of it might be having to load the Google Maps API from a remote source.

Doing anything involving maps and HTML/JS will probably take a decent performance hit unfortunately. Maybe it would be worthwhile to explore another framework?

### CODE REVIEW

**Comment by rec** [comment]
On Wed, Feb 15, 2012 at 10:48 PM, Andrew Burgess <
reply@reply.github.com

> wrote:
> 
> I've set up the necessary framework using jQuery Mobile

Oh, right on!  Now I feel slack for working on music tonight!  :-D

> One thing I've noticed though is that it's kind of slow on my Android
> phone (original Droid). If that's not a huge deal at the moment, then I
> will continue along. I think part of it might be having to load the Google
> Maps API from a remote source.

Oh, dear.  :-(

Well, how big is the Google Maps API as a download?

> Doing anything involving maps and HTML/JS will probably take a decent
> performance hit unfortunately. Maybe it would be worthwhile to explore
> another framework?

What other choices do we have?

"Slow maps" would be a bad feature out of the gate...

**Comment by andrewburgess** [comment]
I'll experiment with a few options. iOS has a Phonegap plugin to allow native Maps within the application, but Android does not. I may be able to create a native Activity for Android that would essentially be the map page using the native framework.

If I can't seem to get this to work, we may need to explore alternatives. I'll let you know as soon as I can

**Comment by wsirota** [comment]
Maybe this is naive, but I don't suppose there's a way to cache the maps api locally so that it's slow the first time, but not thereafter?

**Comment by andrewburgess** [comment]
I can look into that as well

**Comment by wsirota** [comment]
one additional reason why caching the api, if it works, would be superior
to custom-coded widgets for each platform is that Android and iOS are not
the only two platforms, although they are by far the  most important, and
they will be sufficient if we're forced to only choose them

On Thu, Feb 16, 2012 at 7:26 AM, Andrew Burgess <
reply@reply.github.com

> wrote:
> 
> I can look into that as well
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rec/mop/pull/2#issuecomment-4000528

## 

Warren
http://www.warrensirota.com
NEW CD: Loops, Live & Otw
http://www.cdbaby.com/cd/warrensirota

**Comment by rec** [comment]
So to summarize:
1. PhoneGap _does_ allow native iOS maps.
2. PhoneGap _does not_ allow native Android maps.
3. We might be able to use a plug-in to get the equivalent of native
   Android maps.
4. We don't know if _any_ system allows us to do native Android maps.
5. Caching the JS API might allow for better performance of PhoneGap on
   Android.
6. Caching might also be a viable solution for phones that aren't iPhone or
   Android.

**Comment by andrewburgess** [comment]
1. Correct
2. Correct
3. iOS has MapKit, which seems to allow an embedded native map
4. There is nothing that I've seen that would allow native maps in Android
5. We could attempt caching, but I'm not sure if it will even be possible yet
6. We can still use the web based maps for other platforms.

My thought is that we can use the MapKit plugin for iOS. Then, for Android, use the WebIntent plugin which could maybe let us start up a native Activity with a map view. Finally, if it's another system, we can just default to the default Google Maps implementation.

Using the WebIntents plugin for Android will let us communicate between the phonegap application and natively implemented activities

**Comment by wsirota** [comment]
I take it you've looked at Android MapView, touted here
http://www.mail-archive.com/google-maps-api@googlegroups.com/msg57212.html
as the android equivalent to mapkit (they might mean "equivalent" logically
but not in a way that helps us)

On Thu, Feb 16, 2012 at 10:06 AM, Andrew Burgess <
reply@reply.github.com

> wrote:
> 1. Correct
> 2. Correct
> 3. iOS has MapKit, which seems to allow an embedded native map
> 4. There is nothing that I've seen that would allow native maps in Android
> 5. We could attempt caching, but I'm not sure if it will even be possible
>    yet
> 6. We can still use the web based maps for other platforms.
> 
> My thought is that we can use the MapKit plugin for iOS. Then, for
> Android, use the WebIntent plugin which could maybe let us start up a
> native Activity with a map view. Finally, if it's another system, we can
> just default to the default Google Maps implementation.
> 
> Using the WebIntents plugin for Android will let us communicate between
> the phonegap application and natively implemented activities
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rec/mop/pull/2#issuecomment-4003427

## 

Warren
http://www.warrensirota.com
NEW CD: Loops, Live & Otw
http://www.cdbaby.com/cd/warrensirota

**Comment by andrewburgess** [comment]
Correct. You may remember the storefinder I implemented on Android last year: https://github.com/andrewburgess/Store-Finder/blob/master/src/com/parse3/storefinder/views/MapStoresActivity.java

**Pull request merged**
